// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "github.com/GrantZheng/monolith_demo/sensitive_words/pkg/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	CheckWordsEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.SensitiveWordsService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{CheckWordsEndpoint: MakeCheckWordsEndpoint(s)}
	for _, m := range mdw["CheckWords"] {
		eps.CheckWordsEndpoint = m(eps.CheckWordsEndpoint)
	}
	return eps
}
