// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "github.com/GrantZheng/monolith_demo/gift/pkg/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	GiveEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.GiftService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{GiveEndpoint: MakeGiveEndpoint(s)}
	for _, m := range mdw["Give"] {
		eps.GiveEndpoint = m(eps.GiveEndpoint)
	}
	return eps
}
